### ISSUE TITLE
Вопросы по main

### ISSUE THREAD

**Issue by kazantsev-roman** [Andreanapolicy/Recursive-Descent#1]
1. Проверка на PROG будет в main? Решили же, что в Prog.h
https://github.com/Andreanapolicy/Recursive-Descent/blob/940aca4d6237212e03484a0d0f5b16c6534a86a8/main.cpp#L28

2. Надо бы вернуть получаемое значение, или всегда будет возвращаться false
https://github.com/Andreanapolicy/Recursive-Descent/blob/940aca4d6237212e03484a0d0f5b16c6534a86a8/main.cpp#L30

**Comment by Andreanapolicy** [comment]
Всем ку в этом чатике. Отвечаю на вопросы
1. Да, будет. Логика такая: в main проверяю, что есть слово `PROG` -> запускаю `executeProg`. Если ключевого слова нет -> падает false
2. Поправлю. Еще не приступал :)

**Comment by Andreanapolicy** [comment]
Ответил на вопросы. Доп не последовало -> закрываю
